version: '3.8'
services:
  api:
    build: .
    ports:
      - "8090:80"
  db:
    image: postgres:15-alpine
    ports:
      - "49512:5432"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "49490:5432"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
