version: '3.8'
services:
  app:
    build: ./path-to-react-app
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./path-to-symfony-api
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
