version: '3.8'
services:
  api:
    image: my-api-api
    ports:
      - "8090:80"
    depends_on:
      - db
    build: .
    ports:
      - "8090:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
      APP_ENV: dev 
    volumes:
      - .:/var/www/html

  db:
    image: postgres:15-alpine
    ports:
      - "49512:5432"
    environment:
     POSTGRES_USER: app
      POSTGRES_PASSWORD: !ChangeMe!
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
