# Utiliser une image PHP officielle comme base
FROM php:8.1-apache

# Installer les extensions PHP nécessaires
RUN apt-get update && apt-get install -y \
        libpq-dev \
    && docker-php-ext-install \
        pdo pdo_pgsql

RUN a2enmod rewrite
RUN echo '<Directory /var/www/html>\n\tAllowOverride All\n</Directory>' >> /etc/apache2/apache2.conf

# Copier les fichiers du projet dans le conteneur
COPY . /var/www/html

# Définir les permissions des dossiers
RUN chown -R www-data:www-data /var/www/html

# Exposer le port 80
EXPOSE 80
