lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem' # clé publique
    pass_phrase: 'your_password' # La passphrase pour la clé privée
    token_ttl: 3600
